name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore the application
      run: msbuild hosts.sln /t:Restore /p:Configuration="Release"

    - name: Build the solution
      run: msbuild hosts.sln /p:Configuration="Release" /p:platform="Any CPU"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bin
        path: hosts\bin\Release
